import { PokemonDetail } from "../types";

export const pikachu: PokemonDetail = {
  id: 25,
  name: "pikachu",
  types: ["electric"],
  image:
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
  weight: 60,
  height: 4,
  base_experience: 112,
  forms: ["pikachu"],
  abilities: ["static", "lightning-rod"],
  stats: {
    hp: 35,
    attack: 55,
    defense: 40,
    "special-attack": 50,
    "special-defense": 50,
    speed: 90,
  },
};

export const pokemonListMock: PokemonDetail[] = [
  {
    id: 16,
    name: "pidgey",
    types: ["normal", "flying"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
    weight: 18,
    height: 3,
    base_experience: 50,
    forms: ["pidgey"],
    abilities: ["keen-eye", "tangled-feet", "big-pecks"],
    stats: {
      hp: 40,
      attack: 45,
      defense: 40,
      "special-attack": 35,
      "special-defense": 35,
      speed: 56,
    },
  },
  {
    id: 17,
    name: "pidgeotto",
    types: ["normal", "flying"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
    weight: 300,
    height: 11,
    base_experience: 122,
    forms: ["pidgeotto"],
    abilities: ["keen-eye", "tangled-feet", "big-pecks"],
    stats: {
      hp: 63,
      attack: 60,
      defense: 55,
      "special-attack": 50,
      "special-defense": 50,
      speed: 71,
    },
  },
  {
    id: 18,
    name: "pidgeot",
    types: ["normal", "flying"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
    weight: 395,
    height: 15,
    base_experience: 216,
    forms: ["pidgeot"],
    abilities: ["keen-eye", "tangled-feet", "big-pecks"],
    stats: {
      hp: 83,
      attack: 80,
      defense: 75,
      "special-attack": 70,
      "special-defense": 70,
      speed: 101,
    },
  },
  {
    id: 19,
    name: "rattata",
    types: ["normal"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
    weight: 35,
    height: 3,
    base_experience: 51,
    forms: ["rattata"],
    abilities: ["run-away", "guts", "hustle"],
    stats: {
      hp: 30,
      attack: 56,
      defense: 35,
      "special-attack": 25,
      "special-defense": 35,
      speed: 72,
    },
  },
  {
    id: 20,
    name: "raticate",
    types: ["normal"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",
    weight: 185,
    height: 7,
    base_experience: 145,
    forms: ["raticate"],
    abilities: ["run-away", "guts", "hustle"],
    stats: {
      hp: 55,
      attack: 81,
      defense: 60,
      "special-attack": 50,
      "special-defense": 70,
      speed: 97,
    },
  },
  {
    id: 21,
    name: "spearow",
    types: ["normal", "flying"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png",
    weight: 20,
    height: 3,
    base_experience: 52,
    forms: ["spearow"],
    abilities: ["keen-eye", "sniper"],
    stats: {
      hp: 40,
      attack: 60,
      defense: 30,
      "special-attack": 31,
      "special-defense": 31,
      speed: 70,
    },
  },
  {
    id: 22,
    name: "fearow",
    types: ["normal", "flying"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png",
    weight: 380,
    height: 12,
    base_experience: 155,
    forms: ["fearow"],
    abilities: ["keen-eye", "sniper"],
    stats: {
      hp: 65,
      attack: 90,
      defense: 65,
      "special-attack": 61,
      "special-defense": 61,
      speed: 100,
    },
  },
  {
    id: 23,
    name: "ekans",
    types: ["poison"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png",
    weight: 69,
    height: 20,
    base_experience: 58,
    forms: ["ekans"],
    abilities: ["intimidate", "shed-skin", "unnerve"],
    stats: {
      hp: 35,
      attack: 60,
      defense: 44,
      "special-attack": 40,
      "special-defense": 54,
      speed: 55,
    },
  },
  {
    id: 24,
    name: "arbok",
    types: ["poison"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png",
    weight: 650,
    height: 35,
    base_experience: 157,
    forms: ["arbok"],
    abilities: ["intimidate", "shed-skin", "unnerve"],
    stats: {
      hp: 60,
      attack: 95,
      defense: 69,
      "special-attack": 65,
      "special-defense": 79,
      speed: 80,
    },
  },
  {
    id: 25,
    name: "pikachu",
    types: ["electric"],
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    weight: 60,
    height: 4,
    base_experience: 112,
    forms: ["pikachu"],
    abilities: ["static", "lightning-rod"],
    stats: {
      hp: 35,
      attack: 55,
      defense: 40,
      "special-attack": 50,
      "special-defense": 50,
      speed: 90,
    },
  },
];
